const farmersData = [
    {
      name: 'John Doe',
      age: 45,
      gender: 'Male',
      experience: 20,
      language: 'English, Hindi',
      crops: 'Wheat, Rice',
      equipmentKnowledge: 'Tractors, Plows',
      helpers: 5,
      village: 'Greenfield',
    },
    {
      name: 'Jane Smith',
      age: 35,
      gender: 'Female',
      experience: 10,
      language: 'English, Spanish',
      crops: 'Corn, Soybeans',
      equipmentKnowledge: 'Harvesters, Seeders',
      helpers: 3,
      village: 'Sunville',
    },
    {
      name: 'Rajesh Kumar',
      age: 50,
      gender: 'Male',
      experience: 25,
      language: 'Hindi, English',
      crops: 'Sugarcane, Cotton',
      equipmentKnowledge: 'Plows, Sprayers',
      helpers: 8,
      village: 'Harveston',
    },
    {
      name: 'Aisha Khan',
      age: 40,
      gender: 'Female',
      experience: 15,
      language: 'Urdu, English',
      crops: 'Vegetables, Fruits',
      equipmentKnowledge: 'Tractors, Harvesters',
      helpers: 4,
      village: 'Riverside',
    },
    {
      name: 'Mohammed Ali',
      age: 38,
      gender: 'Male',
      experience: 12,
      language: 'Arabic, English',
      crops: 'Dates, Olives',
      equipmentKnowledge: 'Seeders, Plows',
      helpers: 2,
      village: 'Hillside',
    },
    {
      name: 'Sunita Patel',
      age: 30,
      gender: 'Female',
      experience: 7,
      language: 'Gujarati, Hindi',
      crops: 'Spices, Rice',
      equipmentKnowledge: 'Threshers, Harvesters',
      helpers: 6,
      village: 'Meadowbrook',
    },
    {
      name: 'Carlos Ruiz',
      age: 47,
      gender: 'Male',
      experience: 22,
      language: 'Spanish, English',
      crops: 'Coffee, Bananas',
      equipmentKnowledge: 'Tractors, Sprayers',
      helpers: 9,
      village: 'Oakwood',
    },
    {
      name: 'Emily Johnson',
      age: 33,
      gender: 'Female',
      experience: 9,
      language: 'English',
      crops: 'Apples, Grapes',
      equipmentKnowledge: 'Pruners, Seeders',
      helpers: 3,
      village: 'Willowcreek',
    },
    {
      name: 'Li Wei',
      age: 42,
      gender: 'Male',
      experience: 18,
      language: 'Mandarin, English',
      crops: 'Rice, Tea',
      equipmentKnowledge: 'Harvesters, Plows',
      helpers: 7,
      village: 'Pineview',
    },
    {
      name: 'Fatima Begum',
      age: 36,
      gender: 'Female',
      experience: 13,
      language: 'Bengali, Hindi',
      crops: 'Jute, Vegetables',
      equipmentKnowledge: 'Tractors, Seeders',
      helpers: 5,
      village: 'Cedarville',
    },
    {
      name: 'Ahmed Hussein',
      age: 55,
      gender: 'Male',
      experience: 30,
      language: 'Arabic, Urdu',
      crops: 'Dates, Citrus',
      equipmentKnowledge: 'Sprayers, Harvesters',
      helpers: 10,
      village: 'Lakeside',
    },
    {
      name: 'Ravi Shankar',
      age: 29,
      gender: 'Male',
      experience: 5,
      language: 'Telugu, English',
      crops: 'Millet, Sorghum',
      equipmentKnowledge: 'Threshers, Plows',
      helpers: 4,
      village: 'Brookside',
    },
    {
      name: 'Maria Garcia',
      age: 41,
      gender: 'Female',
      experience: 16,
      language: 'Spanish, Portuguese',
      crops: 'Corn, Wheat',
      equipmentKnowledge: 'Tractors, Seeders',
      helpers: 6,
      village: 'Riverview',
    },
    {
      name: 'Yuki Nakamura',
      age: 34,
      gender: 'Female',
      experience: 11,
      language: 'Japanese, English',
      crops: 'Rice, Vegetables',
      equipmentKnowledge: 'Harvesters, Sprayers',
      helpers: 3,
      village: 'Sunnyvale',
    },
    {
      name: 'Paul Anderson',
      age: 50,
      gender: 'Male',
      experience: 26,
      language: 'English, French',
      crops: 'Potatoes, Carrots',
      equipmentKnowledge: 'Plows, Harvesters',
      helpers: 5,
      village: 'Hilltop',
    },
    {
      name: 'Nisha Kapoor',
      age: 27,
      gender: 'Female',
      experience: 4,
      language: 'Hindi, English',
      crops: 'Spices, Herbs',
      equipmentKnowledge: 'Threshers, Pruners',
      helpers: 2,
      village: 'Valleyview',
    },
    {
      name: 'Jorge Santos',
      age: 48,
      gender: 'Male',
      experience: 23,
      language: 'Spanish, English',
      crops: 'Avocados, Beans',
      equipmentKnowledge: 'Tractors, Sprayers',
      helpers: 8,
      village: 'Maplewood',
    },
    {
      name: 'Sofia Alvarez',
      age: 39,
      gender: 'Female',
      experience: 14,
      language: 'Spanish, French',
      crops: 'Cocoa, Coffee',
      equipmentKnowledge: 'Seeders, Harvesters',
      helpers: 7,
      village: 'Elmwood',
    },
    {
      name: 'Chen Liu',
      age: 32,
      gender: 'Male',
      experience: 9,
      language: 'Mandarin, English',
      crops: 'Tea, Bamboo',
      equipmentKnowledge: 'Plows, Sprayers',
      helpers: 3,
      village: 'Bayview',
    },
    {
      name: 'Sara Khan',
      age: 37,
      gender: 'Female',
      experience: 12,
      language: 'Urdu, Hindi',
      crops: 'Cotton, Wheat',
      equipmentKnowledge: 'Tractors, Seeders',
      helpers: 4,
      village: 'Groveville',
    },
  ];
  
  export default farmersData;
  