export const fieldsData = [
    {
        area: 5000,
        estimatedPrice: 200000,
        village: 'Meadowbrook',
        soilInfo: 'Loamy',
        rainfallAvg: 500,
        pastYield: 'High',
        growableCrops: 'Rice, Wheat',
        irrigationFacilities: 'Drip, Canal',
    },
    {
        area: 3000,
        estimatedPrice: 150000,
        village: 'Pineview',
        soilInfo: 'Clayey',
        rainfallAvg: 600,
        pastYield: 'Medium',
        growableCrops: 'Corn, Soybeans',
        irrigationFacilities: 'Sprinkler, Flood',
    },
    {
        area: 4500,
        estimatedPrice: 180000,
        village: 'Greenfield',
        soilInfo: 'Sandy',
        rainfallAvg: 450,
        pastYield: 'Low',
        growableCrops: 'Barley, Oats',
        irrigationFacilities: 'Drip, Center Pivot',
    },
    {
        area: 5200,
        estimatedPrice: 210000,
        village: 'Hilltop',
        soilInfo: 'Peaty',
        rainfallAvg: 550,
        pastYield: 'High',
        growableCrops: 'Wheat, Corn',
        irrigationFacilities: 'Flood, Drip',
    },
    {
        area: 3800,
        estimatedPrice: 160000,
        village: 'Riverdale',
        soilInfo: 'Silty',
        rainfallAvg: 480,
        pastYield: 'Medium',
        growableCrops: 'Rice, Sugarcane',
        irrigationFacilities: 'Canal, Sprinkler',
    },
    {
        area: 6100,
        estimatedPrice: 250000,
        village: 'Valleyview',
        soilInfo: 'Chalky',
        rainfallAvg: 700,
        pastYield: 'Very High',
        growableCrops: 'Grapes, Vegetables',
        irrigationFacilities: 'Drip, Furrow',
    },
    {
        area: 2700,
        estimatedPrice: 120000,
        village: 'Sunnydale',
        soilInfo: 'Sandy Loam',
        rainfallAvg: 530,
        pastYield: 'Medium',
        growableCrops: 'Tomatoes, Peppers',
        irrigationFacilities: 'Sprinkler, Drip',
    },
    {
        area: 3300,
        estimatedPrice: 140000,
        village: 'Oakwood',
        soilInfo: 'Clay Loam',
        rainfallAvg: 600,
        pastYield: 'High',
        growableCrops: 'Cotton, Soybeans',
        irrigationFacilities: 'Flood, Sprinkler',
    },
    {
        area: 4000,
        estimatedPrice: 175000,
        village: 'Lakeside',
        soilInfo: 'Loamy Sand',
        rainfallAvg: 450,
        pastYield: 'Low',
        growableCrops: 'Peanuts, Maize',
        irrigationFacilities: 'Drip, Canal',
    },
    {
        area: 2900,
        estimatedPrice: 130000,
        village: 'Elmwood',
        soilInfo: 'Silty Clay',
        rainfallAvg: 620,
        pastYield: 'Medium',
        growableCrops: 'Barley, Sunflower',
        irrigationFacilities: 'Furrow, Sprinkler',
    },
    {
        area: 4800,
        estimatedPrice: 190000,
        village: 'Brookside',
        soilInfo: 'Peaty Loam',
        rainfallAvg: 510,
        pastYield: 'High',
        growableCrops: 'Rice, Vegetables',
        irrigationFacilities: 'Drip, Flood',
    },
    {
        area: 3200,
        estimatedPrice: 145000,
        village: 'Willow Creek',
        soilInfo: 'Clayey Sand',
        rainfallAvg: 560,
        pastYield: 'Medium',
        growableCrops: 'Corn, Soybeans',
        irrigationFacilities: 'Sprinkler, Drip',
    },
    {
        area: 5300,
        estimatedPrice: 230000,
        village: 'Cedar Grove',
        soilInfo: 'Sandy Clay',
        rainfallAvg: 670,
        pastYield: 'High',
        growableCrops: 'Wheat, Grapes',
        irrigationFacilities: 'Furrow, Drip',
    },
    {
        area: 3500,
        estimatedPrice: 160000,
        village: 'Maplewood',
        soilInfo: 'Chalky Loam',
        rainfallAvg: 590,
        pastYield: 'Medium',
        growableCrops: 'Oats, Barley',
        irrigationFacilities: 'Sprinkler, Flood',
    },
    {
        area: 4100,
        estimatedPrice: 185000,
        village: 'Evergreen',
        soilInfo: 'Loamy Clay',
        rainfallAvg: 500,
        pastYield: 'Low',
        growableCrops: 'Peanuts, Tomatoes',
        irrigationFacilities: 'Canal, Drip',
    },
    {
        area: 5500,
        estimatedPrice: 240000,
        village: 'Pine Hill',
        soilInfo: 'Silty Loam',
        rainfallAvg: 650,
        pastYield: 'High',
        growableCrops: 'Rice, Sugarcane',
        irrigationFacilities: 'Flood, Sprinkler',
    },
    {
        area: 3700,
        estimatedPrice: 155000,
        village: 'Birchwood',
        soilInfo: 'Clayey Loam',
        rainfallAvg: 540,
        pastYield: 'Medium',
        growableCrops: 'Corn, Vegetables',
        irrigationFacilities: 'Drip, Canal',
    },
    {
        area: 4600,
        estimatedPrice: 195000,
        village: 'Cloverfield',
        soilInfo: 'Loamy Sand',
        rainfallAvg: 480,
        pastYield: 'Low',
        growableCrops: 'Wheat, Maize',
        irrigationFacilities: 'Sprinkler, Furrow',
    },
    {
        area: 2800,
        estimatedPrice: 125000,
        village: 'Meadowlark',
        soilInfo: 'Sandy Loam',
        rainfallAvg: 520,
        pastYield: 'Medium',
        growableCrops: 'Soybeans, Peppers',
        irrigationFacilities: 'Drip, Flood',
    },
    {
        area: 5400,
        estimatedPrice: 220000,
        village: 'Aspen Grove',
        soilInfo: 'Peaty Sand',
        rainfallAvg: 600,
        pastYield: 'High',
        growableCrops: 'Grapes, Sunflower',
        irrigationFacilities: 'Furrow, Sprinkler',
    },
];
